### ISSUE TITLE
README.md is not in the tarball

### ISSUE THREAD

**Issue by hroncok** [sjkingo/virtualenv-api#21]
Steps to reproduce:

 1. Go to https://pypi.python.org/pypi/virtualenv-api
 * Download https://pypi.python.org/packages/source/v/virtualenv-api/virtualenv-api-2.1.7.tar.gz
 * Unpack it and cd in
 * `virtualenv-3.4 .env`
 * `. .env/bin/activate`
 * `python setup.py install`

Actual result:

```
Installed /home/churchyard/tmp/virtualenv-api-2.1.7/.eggs/pypandoc-1.1.3-py3.4.egg
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    packages=find_packages(),
  File "/usr/lib64/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/churchyard/tmp/virtualenv-api-2.1.7/.env/lib/python3.4/site-packages/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/home/churchyard/tmp/virtualenv-api-2.1.7/.env/lib/python3.4/site-packages/setuptools/dist.py", line 325, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/churchyard/tmp/virtualenv-api-2.1.7/.eggs/setuptools_markdown-0.2-py3.4.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
    output = pypandoc.convert(markdown_filename, 'rst')
  File "/home/churchyard/tmp/virtualenv-api-2.1.7/.eggs/pypandoc-1.1.3-py3.4.egg/pypandoc/__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "/home/churchyard/tmp/virtualenv-api-2.1.7/.eggs/pypandoc-1.1.3-py3.4.egg/pypandoc/__init__.py", line 68, in _convert
    raise RuntimeError('Missing format!')
RuntimeError: Missing format!
```

The error above says Missing format, but is actually about a missing file. See https://github.com/bebraw/pypandoc/issues/86

Excepted result: Installs.

See also https://github.com/fedora-python/pyp2rpm/issues/27 and https://github.com/msabramo/setuptools-markdown/issues/7#issuecomment-165172625

**Comment by hroncok** [comment]
I'll send a PR.

**Comment by sjkingo** [comment]
Thanks for the detailed report and PR.

The problem is: this still breaks (at least in the tests)! And really, the issue you raised shouldn't happen at all. There seems to be some missing dependency of `setuptools-markdown` that is no longer on pypi.

I think the "correct" solution to this is converting the `README.md` markdown to an rST document, which pypi natively recognises. We can then remove the setup dependency of `setuptools-markdown`, and this problem should go away.

What do you think?

**Comment by hroncok** [comment]
That would actually be much better, yes.

**Comment by sjkingo** [comment]
Can you try now, 2.1.8 is on Pypi which should fix the issue you're having.
