### ISSUE TITLE
Package install hangs

### ISSUE THREAD

**Issue by alinlacea** [sjkingo/virtualenv-api#43]
I am trying to create a new virtual env and install a specific package (**paramiko==1.7.7.1**), but it seems that every time I do that, the installation hangs in a specific point.

My setup:

```
import shutil

from virtualenvapi.manage import VirtualEnvironment

if __name__ == '__main__':
    venv = VirtualEnvironment('./bla-env')
    venv.install(('paramiko', '1.7.7.1'), options=['--no-cache'])
    print venv.installed_packages
    shutil.rmtree('./bla-env')
```

Using PyCharm, I have been able to track down where it hangs:
```
Traceback (most recent call last):
  File "/home/alacea/pycharm-2018.3.5/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/alacea/pycharm-2018.3.5/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/alacea/pycharm-2018.3.5/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/alacea/test-venv/src/vapi-test.py", line 7, in <module>
    venv.install(('paramiko', '1.7.7.1'), options=['--no-cache'])
  File "/home/alacea/test-venv/env/lib/python2.7/site-packages/virtualenvapi/manage.py", line 223, in install
    self._execute_pip(['install'] + package_args + options)
  File "/home/alacea/test-venv/env/lib/python2.7/site-packages/virtualenvapi/manage.py", line 127, in _execute_pip
    return self._execute(exec_args, log=log)
  File "/home/alacea/test-venv/env/lib/python2.7/site-packages/virtualenvapi/manage.py", line 137, in _execute
    output, error = proc.communicate()
  File "/opt/test/base/lib/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/opt/test/base/lib/python2.7/subprocess.py", line 1124, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/opt/test/base/lib/python2.7/subprocess.py", line 1178, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
```
Do you have any idea what might be causing this?

Installing the same package from the CLI (--no-cache as well) works just fine. I didn't come across other packages causing this so far.

**Comment by alinlacea** [comment]
Apparently PyCharm is actually the culprit here. Running the same script from the CLI works fine. I'll investigate further & i'll come back if there's anything relevant to this package.

**Comment by alinlacea** [comment]
Fixed, nothing related to the virtualenv-api package. I'll just leave this here if anyone comes across the same issue. The fix can be found at: https://github.com/fabric/fabric/issues/958#issuecomment-60308187

**Comment by sjkingo** [comment]
Nice catch! Glad you figured it out.
